In [1]:
import pandas as pd
import numpy as np

In [2]:
carprices = pd.read_pickle('CarPricesData.pkl')

In [3]:
carprices.head()

Age     KM  Weight  HP  MetColor      CC  Doors  Price
0  23.0  46986  1165.0  90         1  2000.0      3  13500
1  23.0  72937  1165.0  90         1  2000.0      3  13750
2  24.0  41711  1165.0  90         1  2000.0      3  13950
3  26.0  48000  1165.0  90         0  2000.0      3  14950
4  30.0  38500  1170.0  90         0  2000.0      3  13750

In [4]:
TargetVariable = ['Price']
Predictors = ['Age','KM','Weight','HP','MetColor','CC','Doors']

In [12]:
X = carprices[Predictors].values

In [33]:
X
print(X.shape)

(1435, 7)


In [21]:
Y = carprices[TargetVariable].values

In [34]:
Y
print(Y.shape)

(1435, 1)


we are standardizing the data as well. This is important for Neural Networks because it improves the model training speed and helps to find global minima.



In [23]:
from sklearn.preprocessing import StandardScaler
PredictorScaler = StandardScaler()
TargetVarScaler = StandardScaler()

In [24]:
PredictorScaler

StandardScaler()

In [25]:
PredictorScalerFit = PredictorScaler.fit(X)
TargetVarScalerFit = TargetVarScaler.fit(Y)

In [26]:
PredictorScalerFit

StandardScaler()

In [28]:
X = PredictorScalerFit.transform(X)
Y = TargetVarScalerFit.transform(Y)

In [29]:
X

array([[ -3.1203912 ,  -1.82966821, -22.43884106, ...,   0.04271404,
         -8.37920472,  -5.37331689],
       [ -3.1203912 ,  -1.82964973, -22.43884106, ...,   0.04271404,
         -8.37920472,  -5.37331689],
       [ -3.1174777 ,  -1.82967196, -22.43884106, ...,   0.04271404,
         -8.37920472,  -5.37331689],
       ...,
       [ -2.98054353,  -1.82968955, -22.50484449, ...,  -4.51252912,
         -8.3992864 ,  -5.37331689],
       [ -2.98345703,  -1.82968962, -22.50484449, ...,   0.04271404,
         -8.3992864 ,  -5.37331689],
       [ -2.96597607,  -1.82970166, -22.46128223, ...,  -4.51252912,
         -8.39067996,  -3.16810227]])

In [30]:
Y

array([[ 0.77036821],
       [ 0.83966875],
       [ 0.89510918],
       ...,
       [-0.61564265],
       [-0.96214536],
       [-1.04530601]])

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3, random_state=42)

In [32]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(1004, 7)
(1004, 1)
(431, 7)
(431, 1)


In [35]:
# !pip install tensorflow
# !pip install keras

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.3/588.3 MB 674.6 kB/s eta 0:00:00m eta 0:00:010:00:05
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 2.9 MB/s eta 0:00:00m eta 0:00:010:01:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 2.9 MB/s eta 0:00:00m eta 0:00:010:01:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 2.9 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.2/439.2 kB 2.3 MB/s eta 0:00:000:00:010:00:01:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 3.0 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 2.5 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.7/75.7 kB 834.3 kB/s eta 0:00:0031m15.6 MB/s eta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 2.9 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━

  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.7/151.7 kB 1.1 MB/s eta 0:00:0031m10.3 MB/s eta 0:00:01
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      Successfully uninstalled protobuf-3.20.3

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python3 -m pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python3 -m pip install --upgrade pip


In [44]:
from keras.models import Sequential
from keras.layers import Dense


model = Sequential()

model.add(Dense(units = 5, input_dim = 7, kernel_initializer='normal', activation = 'relu'))

model.add(Dense(units = 5, kernel_initializer = 'normal', activation = 'tanh'))

model.add(Dense(units = 1,kernel_initializer = 'normal'))

model.compile(loss = 'mean_squared_error', optimizer = 'adam')

model.fit(X_train,Y_train, batch_size = 20, epochs = 50, verbose = 1)

Epoch 1/50
51/51 [==============================] - 1s 2ms/step - loss: 0.9865
Epoch 2/50
51/51 [==============================] - 0s 2ms/step - loss: 0.9859
Epoch 3/50
51/51 [==============================] - 0s 2ms/step - loss: 0.9854
Epoch 4/50
51/51 [==============================] - 0s 2ms/step - loss: 0.9844
Epoch 5/50
51/51 [==============================] - 0s 2ms/step - loss: 0.9813
Epoch 6/50
51/51 [==============================] - 0s 2ms/step - loss: 0.9788
Epoch 7/50
51/51 [==============================] - 0s 2ms/step - loss: 0.9783
Epoch 8/50
51/51 [==============================] - 0s 2ms/step - loss: 0.9700
Epoch 9/50
51/51 [==============================] - 0s 2ms/step - loss: 0.9661
Epoch 10/50
51/51 [==============================] - 0s 2ms/step - loss: 0.9620
Epoch 11/50
51/51 [==============================] - 0s 2ms/step - loss: 0.9598
Epoch 12/50
51/51 [==============================] - 0s 2ms/step - loss: 0.9673
Epoch 13/50
51/51 [==============================

In [45]:
Predictions = model.predict(X_test)

14/14 [==============================] - 0s 1ms/step


In [46]:
Predictions = TargetVarScalerFit.inverse_transform(Predictions)

In [48]:
Predictions.shape

(431, 1)

In [49]:
Y_test_original = TargetVarScalerFit.inverse_transform(Y_test)

In [50]:
Y_test_original

array([[ 9950.],
       [ 7995.],
       [ 7500.],
       [ 9950.],
       [ 8950.],
       [ 8995.],
       [ 9450.],
       [ 6750.],
       [11950.],
       [10950.],
       [ 9900.],
       [ 9750.],
       [11480.],
       [11950.],
       [ 8750.],
       [10995.],
       [13950.],
       [16950.],
       [ 7950.],
       [ 9950.],
       [12750.],
       [17650.],
       [ 8250.],
       [10750.],
       [ 8950.],
       [16895.],
       [ 8250.],
       [ 8950.],
       [15950.],
       [14950.],
       [ 7950.],
       [10950.],
       [10950.],
       [ 9450.],
       [10450.],
       [ 8250.],
       [ 8250.],
       [ 8950.],
       [14950.],
       [ 8950.],
       [ 9750.],
       [ 8950.],
       [12950.],
       [ 8500.],
       [ 9950.],
       [16950.],
       [10750.],
       [ 8750.],
       [10750.],
       [14350.],
       [11950.],
       [ 6750.],
       [15750.],
       [17950.],
       [ 7950.],
       [ 9950.],
       [11450.],
       [10750.],
       [18750.

In [52]:
Test_Data = PredictorScalerFit.inverse_transform(X_test)

In [53]:
df = pd.DataFrame(data = Test_Data, columns = Predictors)
df['Price'] = Y_test_original
df['Predictions'] = Predictions
df.head()

Age        KM    Weight        HP  MetColor        CC     Doors  \
0  0.160463  0.316405 -0.139704  0.568103  0.694578  0.178171 -1.084443   
1  0.322394 -0.100720  0.070064  0.568103  0.694578  0.178171  1.015659   
2  0.160463  1.639046  1.328667 -1.969259  0.694578  2.320622 -0.034392   
3  0.700231 -0.687650 -0.454354  0.568103  0.694578  0.178171 -1.084443   
4  0.484324 -0.575211 -1.188540 -1.034441  0.694578 -1.428668 -1.084443   

    Price   Predictions  
0  9950.0  10725.518555  
1  7995.0  12026.280273  
2  7500.0  11385.268555  
3  9950.0  10712.835938  
4  8950.0  10713.192383

In [54]:
error = abs(df['Price'] - df['Predictions'])/df['Price']
error = error * 100

In [56]:
df['error'] = error

In [57]:
df

Age        KM    Weight        HP  MetColor        CC     Doors  \
0    0.160463  0.316405 -0.139704  0.568103  0.694578  0.178171 -1.084443   
1    0.322394 -0.100720  0.070064  0.568103  0.694578  0.178171  1.015659   
2    0.160463  1.639046  1.328667 -1.969259  0.694578  2.320622 -0.034392   
3    0.700231 -0.687650 -0.454354  0.568103  0.694578  0.178171 -1.084443   
4    0.484324 -0.575211 -1.188540 -1.034441  0.694578 -1.428668 -1.084443   
..        ...       ...       ...       ...       ...       ...       ...   
426  0.916138  2.871155  0.070064  0.568103  0.694578  0.178171  1.015659   
427 -2.430422 -1.496124  0.909133  0.568103  0.694578  0.178171  1.015659   
428 -0.001467 -0.889635 -0.978772 -0.299942 -1.439724 -0.893055 -1.084443   
429 -0.001467 -1.314338 -0.978772 -0.299942 -1.439724 -0.893055 -1.084443   
430  0.484324  0.426549  1.014016  0.568103  0.694578  0.178171  1.015659   

       Price   Predictions       error  
0     9950.0  10725.518555    7.794156  
1     7995.0  12026.280273   50.422517  
2     7500.0  11385.268555   51.803581  
3     9950.0  10712.835938    7.666693  
4     8950.0  10713.192383   19.700474  
..       ...           ...         ...  
426   5950.0  12011.471680  101.873474  
427  18900.0  12094.037109   36.010386  
428  10950.0  10010.864258    8.576582  
429  10500.0  10010.865234    4.658426  
430  10950.0  12021.813477    9.788251  

[431 rows x 10 columns]

In [59]:
print("Accuracy of the model is :" ,(100 - np.mean(error)))

Accuracy of the model is : 74.45190935721553


In [62]:
#Finding the best parameters

batch_size = [5,10,15,20]
epochs = [5,10,50,100]

trial = 0
for i in batch_size:
    for j in epochs:
        trial = trial + 1
        model = Sequential()

        model.add(Dense(units = 5, input_dim = 7, kernel_initializer='normal', activation = 'relu'))

        model.add(Dense(units = 5, kernel_initializer = 'normal', activation = 'tanh'))

        model.add(Dense(units = 1,kernel_initializer = 'normal'))

        model.compile(loss = 'mean_squared_error', optimizer = 'adam')

        model.fit(X_train,Y_train, batch_size = i, epochs = j, verbose = 0)
        Predictions = model.predict(X_test)
        Y_test_original = TargetVarScalerFit.inverse_transform(Y_test)
        Test_Data = PredictorScalerFit.inverse_transform(X_test)
        
        df = pd.DataFrame(data = Test_Data, columns = Predictors)
        df['Price'] = Y_test_original
        df['Predictions'] = Predictions
        df['error'] = error
        error = abs(df['Price'] - df['Predictions'])/df['Price']
        error = error * 100
        print(trial,"batch_size",i,"epochs",j,"Accuracy of the model is :" ,(100 - np.mean(error)))
        
        

14/14 [==============================] - 0s 2ms/step
1 batch_size 5 epochs 5 Accuracy of the model is : -3.308405798918557e-05
14/14 [==============================] - 0s 1ms/step
2 batch_size 5 epochs 10 Accuracy of the model is : 0.0001200326807690999
14/14 [==============================] - 0s 2ms/step
3 batch_size 5 epochs 50 Accuracy of the model is : 0.0005713323665617054
14/14 [==============================] - 0s 2ms/step
4 batch_size 5 epochs 100 Accuracy of the model is : -5.293820777296787e-05
14/14 [==============================] - 0s 1ms/step
5 batch_size 10 epochs 5 Accuracy of the model is : 0.00036564243853831613
14/14 [==============================] - 0s 2ms/step
6 batch_size 10 epochs 10 Accuracy of the model is : 0.00042034660559409076
14/14 [==============================] - 0s 1ms/step
7 batch_size 10 epochs 50 Accuracy of the model is : 0.0006378867736032134
14/14 [==============================] - 0s 1ms/step
8 batch_size 10 epochs 100 Accuracy of the model is 